const lessonReviews=[
 {summary:'A trustworthy agent-mediated transaction requires separate evidence that the agent is legitimate, the customer granted authority, and the final action remained within scope.',takeaways:[['Separate the trust questions','Agent identity, customer authorization, and scope compliance answer different questions and require different evidence.'],['Evaluate the complete chain','A valid agent signature or payment approval cannot compensate for missing or out-of-scope customer authority.'],['Design a safe response','When required evidence is missing or conflicting, pause, clarify, step up, or reject according to defined policy.']],next:'In the next lesson, you will focus on agent identity and learn how merchants can distinguish a recognized AI agent from impersonated, altered, stale, or replayed requests.'},
 {summary:'Agent recognition depends on verifiable identity, request integrity, freshness, audience binding, current key status, and protection against replay.',takeaways:[['Use verifiable identity','Connect the request signature and key to a recognized agent through a trusted directory, registry, certificate chain, or onboarding record.'],['Protect the current request','Confirm that critical components are signed and that the request is fresh, correctly addressed, and not reused.'],['Maintain trust status','Define key rotation, revocation, caching, and outage handling so agent identity evidence remains current.']],next:'In the next lesson, you will move from identifying the agent to evaluating what the customer actually allowed that agent to do.'},
 {summary:'Delegated authority should be explicit, bounded, understandable to the customer, and structured so merchants can enforce it consistently.',takeaways:[['Identify every role','Keep the consumer granting authority, the agent acting, and the merchant relying on the grant clearly distinguishable.'],['Structure the scope','Define permitted actions, merchants, products, amounts, time windows, delivery terms, payment methods, and exceptions.'],['Escalate uncertainty','When an instruction cannot be translated confidently or an action exceeds a limit, return to the customer for clarification.']],next:'In the next lesson, you will explore passkeys and step-up verification, including how to bind customer approval to a specific transaction change.'},
 {summary:'Strong authentication verifies participation in an approval event, while transaction binding establishes exactly what the customer approved.',takeaways:[['Use strong authentication at key moments','Enrollment, authority changes, payment setup, risky exceptions, delivery changes, revocation, and disputes may require authentication.'],['Target step-up carefully','Trigger stronger verification for defined material changes or elevated risk rather than applying friction to every transaction.'],['Protect the approval details','Bind merchant, cart, amount, payment, delivery, and timing to the customer’s authenticated confirmation.']],next:'In the next lesson, you will examine how payment tokenization can reduce credential exposure and align payment capability with delegated authority.'},
 {summary:'Tokenization reduces exposure of underlying payment data, but token usability should also be limited to the purpose and scope the customer approved.',takeaways:[['Know which token is present','Network payment tokens and merchant or vault tokens have different issuers, controls, interoperability, and lifecycle responsibilities.'],['Apply least privilege','Use merchant, amount, currency, use-count, time, and scenario restrictions where the payment ecosystem supports them.'],['Plan post-purchase operations','Test capture, retry, split shipment, reversal, refund, return, expiration, renewal, and account-update paths.']],next:'In the next lesson, you will connect customer intent, cart terms, and payment approval through verifiable mandates and real-time authority controls.'},
 {summary:'Consent is a lifecycle. Intent, cart, and payment evidence must remain linked as transaction terms change and authority expires, is replaced, or is revoked.',takeaways:[['Preserve each mandate layer','Intent, cart, and payment mandates record different stages of the customer’s authority.'],['Validate current status','Check authenticity, audience, version, expiration, revocation, and supersession rather than merely storing the record.'],['Act while the order is stoppable','Apply status changes before acceptance, capture, material cart changes, or shipment based on transaction state.']],next:'In the next lesson, you will learn how linked audit evidence supports real-time decisions, investigations, customer service, and disputes.'},
 {summary:'Useful audit evidence tells a coherent, reproducible story while respecting data minimization, access, security, and retention requirements.',takeaways:[['Link the evidence chain','Connect agent verification, customer consent, cart history, payment events, decisions, and fulfillment using stable identifiers.'],['Record why the merchant acted','Preserve verified inputs, missing evidence, policy versions, triggered rules, step-up results, human actions, and reason codes.'],['Operate the controls','Assign ownership, monitor performance and abuse, prepare response procedures, and version schemas and policies.']],next:'In the final Review and Resources lesson, you will revisit the course-wide trust model, review the key controls at a glance, and access primary resources for continued learning.'}
];

function countV4(i=state.lesson){return i===6?4:9}
function labelV4(){if(state.lesson===6)return ['Course Review','Key Takeaways','Resources','Course Completion'][state.screen];return ['Lesson Introduction','Why It Matters','Core Concepts','Merchant Application','Deep Dive','Interactive Activity','Scenario','Knowledge Check','Lesson Review'][state.screen]}
function renderLessonReview(){const r=lessonReviews[state.lesson];return `<section class="screen-panel lesson-review-screen"><span class="screen-eyebrow">Lesson Review</span><h3>Key Takeaways</h3><p class="review-summary">${esc(r.summary)}</p><p class="instruction">Select each takeaway to explore it. Select it again to close it.</p><div class="takeaway-grid">${r.takeaways.map((t,i)=>`<button class="takeaway-card" data-takeaway="${i}" aria-expanded="false"><span class="takeaway-number">${i+1}</span><span class="takeaway-text"><strong>${esc(t[0])}</strong><span>${esc(t[1])}</span></span><span class="takeaway-icon" aria-hidden="true">+</span></button>`).join('')}</div><div class="next-lesson-preview"><span>Coming Next</span><p>${esc(r.next)}</p></div></section>`}
function renderV4(){if(state.lesson<6&&state.screen===8){els.kicker.textContent=`Lesson ${String(state.lesson+1).padStart(2,'0')} of 07 · Lesson Review`;els.title.textContent=lessons[state.lesson].title;els.main.innerHTML=renderLessonReview();$$('.takeaway-card').forEach(b=>b.onclick=()=>{play('click');b.classList.toggle('open');b.setAttribute('aria-expanded',b.classList.contains('open'));b.querySelector('.takeaway-icon').textContent=b.classList.contains('open')?'−':'+'});updateV4();els.main.focus();window.scrollTo(0,0);return}renderV3();if(state.screen===7&&state.lesson<6){$$('[data-kc]').forEach(b=>b.addEventListener('click',()=>setTimeout(updateV4,0)));const match=$('#checkMatch');if(match)match.addEventListener('click',()=>setTimeout(updateV4,0))}updateV4()}
function updateV4(){const review=state.lesson===6,activity=state.screen===5&&!review,scenario=state.screen===6&&!review,kc=state.screen===7&&!review;els.back.disabled=state.lesson===0&&state.screen===0;els.next.disabled=(activity&&!allCardsSeen(state.lesson))||(scenario&&!state.scenarioComplete[state.lesson])||(kc&&!state.kcComplete[state.lesson]);els.next.textContent=state.screen===countV4()-1?(state.lesson===6?'Course Complete':'Next Lesson →'):'Next →';els.indicator.textContent=`Screen ${state.screen+1} of ${countV4()}`;const prior=state.lesson<6?state.lesson*9:54,p=Math.round((prior+state.screen+(state.completed.includes(6)?1:0))/58*100);els.bar.style.width=p+'%';els.pct.textContent=p+'%';els.status.textContent=state.completed.includes(state.lesson)?'Completed':labelV4();renderNavV3()}

$('#startBtn').onclick=()=>{state.started=true;state.lesson=0;state.screen=0;els.start.classList.add('hidden');els.shell.classList.remove('hidden');play('menu');renderV4();save()};$('#resumeBtn').onclick=()=>{state.started=true;els.start.classList.add('hidden');els.shell.classList.remove('hidden');play('menu');renderV4();save()};els.back.onclick=()=>{play('click');if(state.screen>0){state.screen--;renderV4();save()}else if(state.lesson>0){state.lesson--;state.screen=countV4()-1;renderV4();save()}};els.next.onclick=()=>{if(els.next.disabled)return;play('click');if(state.screen<countV4()-1){state.screen++;renderV4();save()}else if(state.lesson<6){state.lesson++;state.screen=0;renderV4();save()}else toast('Course complete. Select Exit Course.')};
