const screenContent=[
 {
  why:["Agent-mediated commerce separates actions that traditionally happened in one customer-controlled session. A consumer may establish instructions on an agent platform, the agent may interact with a merchant hours later, and a payment provider may authorize the final request without the consumer ever opening the merchant site.","This separation creates a new trust problem for merchants. A familiar customer account, a recognized agent, and an approved payment credential can all be valid while the final purchase still falls outside the customer’s instructions."],
  concepts:[['Authentication','Establishes who or what is interacting. For an agent, this may include a cryptographic signature and a trusted identity record.'],['Authorization','Establishes what the authenticated party is permitted to do. It should connect an authenticated consumer to a defined grant of authority.'],['Transaction validation','Compares the actual cart, payment, and fulfillment terms with the authority that was granted.'],['Risk assessment','Evaluates whether valid evidence is still consistent with expected behavior and acceptable merchant risk.']],
  applyTitle:"Evidence Across the Purchase Journey",applyIntro:"Trust evidence should be created and checked throughout the transaction, not assembled only after a dispute.",apply:['Delegation: record the consumer, agent, permitted actions, limits, and expiration.','Selection: preserve the offer and constraints used to choose the item or service.','Cart: bind items, merchant, total, fees, delivery, and substitutions to a version.','Confirmation: record whether the customer or a standing rule approved the final terms.','Payment: link the constrained credential and authorization result to the approved cart.','Fulfillment: evaluate material changes and preserve what was ultimately delivered.']
 },
 {
  why:["Merchants already distinguish helpful automation from scraping, credential attacks, inventory abuse, and other malicious bot activity. Shopping agents add a legitimate form of automation that may browse, negotiate, and buy for a consumer.","A self-declared agent name is not sufficient. Attackers can copy headers, imitate request patterns, or replay a previously valid message. Merchants need evidence that connects the current request to a recognized agent identity and protects critical request details from alteration."],
  concepts:[['Cryptographic signature','Shows that the holder of a private key signed selected request components. The merchant must know which components were protected.'],['Trusted key source','Connects the verification key to a recognized agent through an approved directory, certificate chain, registry, or onboarding record.'],['Freshness','Uses timestamps, nonces, and short validity windows to distinguish a current request from a copied request.'],['Audience binding','Limits a message to the intended merchant, service, endpoint, or transaction context.']],
  applyTitle:"A Merchant Verification Sequence",applyIntro:"Verification should fail safely when required evidence is missing or inconsistent.",apply:['Parse incoming data as untrusted input.','Resolve the agent identity and public key through an approved source.','Verify the signature and confirm that critical request fields are covered.','Validate timestamp, nonce, unique request identifier, and clock tolerance.','Confirm the key and agent registration are active and not revoked.','Check merchant, endpoint, method, cart, and authorization references.','Combine verified identity with authority, scope, and transaction-risk evidence.']
 },
 {
  why:["Delegation allows an agent to act for a consumer without impersonating the consumer. The grant must be specific enough for a merchant to decide whether an action is allowed, not merely broad enough for an agent to interpret creatively.","Natural-language requests are useful for customer experience, but phrases such as ‘find me a good hotel’ or ‘reorder my usual items’ leave important conditions unresolved. Structured limits turn intent into enforceable rules."],
  concepts:[['Principal','The consumer or organization granting authority. The identity should be connected to an authenticated consent event.'],['Agent','The system permitted to perform specified actions. Its identity and current status must be verifiable.'],['Relying merchant','The party evaluating the grant and deciding whether to accept the proposed action.'],['Scope','The actions, merchants, products, amounts, times, delivery terms, payment methods, and exceptions the grant permits.']],
  applyTitle:"Standing and Transaction-Specific Authority",applyIntro:"The appropriate form of delegation depends on how often the action will occur and how much exposure the customer and merchant can accept.",apply:['Standing authority supports repeated actions within stable rules, such as routine replenishment under a monthly limit.','Transaction-specific authority supports one purchase, merchant, item, or time window.','Standing authority requires tighter cumulative limits, monitoring, expiration, and revocation.','Transaction-specific authority narrows exposure but may require more customer confirmation.','When a proposed action exceeds any mandatory limit, request clarification or fresh approval rather than silently expanding the grant.']
 },
 {
  why:["Strong authentication is needed when a customer enrolls an agent, grants or changes authority, adds a payment method, approves an exception, changes delivery information, revokes access, or disputes an action.","A successful authentication event proves that a credential was used. It does not automatically show what the customer saw or approved. The confirmation must be bound to the relevant mandate, cart, amount, merchant, and delivery details."],
  concepts:[['Passkey','A FIDO cryptographic credential tied to an account. It typically uses the same gesture used to unlock a device and is designed to resist phishing.'],['Step-up verification','A request for additional or stronger customer verification when existing evidence is insufficient for the current risk.'],['Transaction binding','Protection that connects the authentication result to the exact details displayed to and approved by the customer.'],['Secure recovery','Fallback and account-recovery processes that do not create an easier way to bypass the primary authentication control.']],
  applyTitle:"When to Request Step-Up",applyIntro:"Use defined risk and scope conditions so that added friction is targeted and explainable.",apply:['The order exceeds an amount, frequency, or category limit.','The cart differs materially from the approved intent.','A new merchant, device, delivery address, or payment credential appears.','A long delay separates the delegation from the purchase.','The product, destination, or transaction pattern carries elevated risk.','Authority has expired, been superseded, or cannot be fully verified.','Do not use customer step-up to repair a failed agent identity check.']
 },
 {
  why:["An agent may interact with multiple merchants, platforms, and service providers. Giving it a reusable primary account number or broadly usable stored credential increases the consequences of compromise.","Tokenization can reduce exposure of underlying payment data and restrict where or how a payment credential works. The strongest design aligns the payment capability with the same merchant, amount, time, and purpose defined in the customer’s authority."],
  concepts:[['Network payment token','An alternative value that replaces a primary account number and may be constrained to a merchant, device, or payment scenario.'],['Merchant or vault token','An internal reference to payment data stored by a merchant or provider. It reduces raw data handling but is not automatically interoperable.'],['Domain controls','Rules that limit where, when, or under which conditions a token can be used.'],['Dynamic data','Transaction-specific cryptographic information that can make copied payment data less reusable.']],
  applyTitle:"Plan the Entire Token Lifecycle",applyIntro:"A token design must support more than the initial authorization.",apply:['Provision and bind the token to the correct consumer, agent, merchant, and mandate.','Apply merchant, amount, currency, use-count, and expiration limits where supported.','Define decline, retry, delayed fulfillment, and partial-shipment behavior.','Support suspension, revocation, expiration, renewal, and underlying account updates.','Maintain safe references for reversals, refunds, returns, and customer service.','Never treat token validity as proof that the final cart matches customer intent.']
 },
 {
  why:["Consent evolves across an agent-mediated purchase. The customer expresses an intent, the agent converts it into a cart, and the payment may occur later. Prices, inventory, fees, delivery terms, or substitutions can change between those stages.","A useful evidence model shows how each material state relates to the next. It also allows authority to expire, be replaced, or be revoked before the merchant takes an action that can no longer be stopped."],
  concepts:[['Intent mandate','Captures the requested outcome and boundaries for autonomous action, such as category, budget, timing, merchant restrictions, and confirmation rules.'],['Cart mandate','Captures the selected merchant, items, quantities, price, fees, delivery, fulfillment terms, and cart version.'],['Payment mandate','Connects approval of a funding source and final amount to the intended recipient and approved cart.'],['Status evidence','Shows whether a mandate is active, expired, revoked, suspended, or replaced by a newer version.']],
  applyTitle:"Real-Time Enforcement Checkpoints",applyIntro:"Check authority near the action being protected, especially when transaction processing takes time.",apply:['Before order acceptance: stop a request whose authority is invalid or unverifiable.','Before payment capture: void or reverse an authorization when feasible after verified revocation.','Before a material cart change: compare the new version with the active scope and request approval when required.','Before shipment: honor a verified change while fulfillment can still be stopped.','After fulfillment: preserve evidence and route the issue through customer service or dispute procedures.','Define how registry or status-service outages fail before the edge case occurs.']
 },
 {
  why:["An audit trail should allow an authorized reviewer to reconstruct who acted, how identity and authority were verified, what the customer permitted, what changed, which controls were evaluated, why the merchant acted, and what was ultimately fulfilled or reversed.","A large volume of disconnected logs is not the same as persuasive evidence. Records become more useful when they share stable transaction identifiers, use synchronized timestamps, preserve verification results, and are protected from unauthorized alteration."],
  concepts:[['Raw event','A request, response, log entry, or system event captured before its trustworthiness has been established.'],['Verified evidence','An event or record whose integrity, source, status, and relationship to the transaction have been validated.'],['Decision record','The policy version, inputs, missing evidence, triggered rules, step-up results, and reason code behind the merchant action.'],['Fulfillment evidence','What was reserved, captured, shipped, canceled, returned, or refunded after the authorization decision.']],
  applyTitle:"Operating Model and Governance",applyIntro:"Trust controls require clear ownership, monitoring, response procedures, and disciplined change management.",apply:['Assign owners across product, payments, fraud, identity, security, privacy, legal, customer service, and operations.','Monitor verification failures, replay attempts, out-of-scope requests, step-up rates, revocations, declines, disputes, and agent-level anomalies.','Create response procedures for compromised keys, registry outages, validation failures, late revocation, token misuse, and missing evidence.','Version schemas, trust lists, policies, and integrations. Do not reinterpret older authority using a broader new schema.','Minimize collected data, restrict access, encrypt sensitive records, and enforce retention and deletion schedules.']
 }
];

state.screen=Number.isInteger(state.screen)?state.screen:0;
state.screenSeen=state.screenSeen||{};

function screenKey(){return `${state.lesson}-${state.screen}`}
function screenCount(){return 6}
function setScreen(n){state.screen=Math.max(0,Math.min(screenCount()-1,n));state.screenSeen[screenKey()]=true;renderV2();save()}
function lessonProgress(){return `${state.screen+1} of ${screenCount()}`}
function sectionLabel(){return ['Lesson Introduction','Why It Matters','Core Concepts','Merchant Application','Interactive Activity','Scenario'][state.screen]}
function conceptGrid(items){return `<div class="concept-grid">${items.map(x=>`<article class="concept-box"><h4>${esc(x[0])}</h4><p>${esc(x[1])}</p></article>`).join('')}</div>`}

function renderV2(){
 const l=lessons[state.lesson],x=screenContent[state.lesson];
 els.kicker.textContent=`Lesson ${String(state.lesson+1).padStart(2,'0')} of ${String(lessons.length).padStart(2,'0')} · ${sectionLabel()}`;
 els.title.textContent=l.title;
 let html='';
 if(state.screen===0) html=`<section class="screen-panel intro-screen"><span class="screen-eyebrow">Lesson ${state.lesson+1}</span><h3>${esc(l.title)}</h3><p class="lead">${esc(l.purpose)}</p><div class="objectives"><h4>By the end of this lesson, you will be able to:</h4><ul>${l.objectives.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div><div class="screen-tip">Select <strong>Next</strong> to begin the lesson.</div></section>`;
 if(state.screen===1) html=`<section class="screen-panel"><span class="screen-eyebrow">Why It Matters</span><h3>The Merchant Trust Challenge</h3>${x.why.map(v=>`<p class="body-copy">${esc(v)}</p>`).join('')}<div class="key-callout"><strong>Key principle:</strong> ${esc(l.key)}</div></section>`;
 if(state.screen===2) html=`<section class="screen-panel"><span class="screen-eyebrow">Core Concepts</span><h3>Build the Foundation</h3><p class="section-lead">These concepts work together. No single signal is sufficient for the full trust decision.</p>${conceptGrid(x.concepts)}</section>`;
 if(state.screen===3) html=`<section class="screen-panel"><span class="screen-eyebrow">Merchant Application</span><h3>${esc(x.applyTitle)}</h3><p class="section-lead">${esc(x.applyIntro)}</p><ol class="application-list">${x.apply.map(v=>`<li>${esc(v)}</li>`).join('')}</ol></section>`;
 if(state.screen===4){const cards=l.cards.map((c,j)=>`<button class="toggle-card ${(state.visitedCards[state.lesson]||[]).includes(j)?'seen':''}" data-card="${j}" aria-expanded="false"><strong>${esc(c[0])}</strong><span class="front-copy">${esc(c[1])}</span><span class="back-copy">${esc(c[2])}</span></button>`).join('');html=`<section class="screen-panel"><span class="screen-eyebrow">Interactive Activity</span><h3>Explore the Controls</h3><p class="instruction">Select each card to reveal more. Select it again to return it to its original state. Review all cards to unlock Next.</p><div class="toggle-grid">${cards}</div><div class="activity-status" role="status">${allCardsSeen(state.lesson)?'Activity complete. You may continue to the scenario.':`${(state.visitedCards[state.lesson]||[]).length} of ${l.cards.length} cards reviewed`}</div></section>`}
 if(state.screen===5){const done=state.completed.includes(state.lesson);html=`<section class="screen-panel scenario-screen"><p class="scenario-intro">${esc(l.scenario.intro)}</p><div class="scenario-card"><div class="character-pane"><img src="assets/character-${state.lesson+1}.png" alt="Professional guiding the scenario"></div><div class="scenario-copy"><h3>Scenario: ${esc(l.scenario.title)}</h3>${l.scenario.body.map(v=>`<p>${esc(v)}</p>`).join('')}<p class="scenario-question">${esc(l.scenario.question)}</p><div class="choice-list">${l.scenario.choices.map((v,j)=>`<button class="choice-btn ${done&&j===l.scenario.correct?'correct':''}" data-choice="${j}" ${done?'disabled':''}>${esc(v)}</button>`).join('')}</div><div class="feedback ${done?'show':''}" role="status"><strong>Correct</strong><br>${esc(l.scenario.feedback)}</div></div></div>${state.lesson===6&&done?`<section class="exit-panel"><h3>You’ve completed the course</h3><p>Please review the course key learnings and resources before exiting to take the final exam.</p><button id="exitBtn" class="primary-btn">Exit Course</button></section>`:''}</section>`}
 els.main.innerHTML=html;
 if(state.screen===4) $$('.toggle-card').forEach(b=>b.onclick=()=>{play('click');b.classList.toggle('open');b.setAttribute('aria-expanded',b.classList.contains('open'));const i=+b.dataset.card;state.visitedCards[state.lesson]=state.visitedCards[state.lesson]||[];if(!state.visitedCards[state.lesson].includes(i))state.visitedCards[state.lesson].push(i);$('.activity-status').textContent=allCardsSeen(state.lesson)?'Activity complete. You may continue to the scenario.':`${state.visitedCards[state.lesson].length} of ${l.cards.length} cards reviewed`;updateV2Chrome();save()});
 if(state.screen===5) $$('.choice-btn').forEach(b=>b.onclick=()=>{play('click');if(+b.dataset.choice===l.scenario.correct){b.classList.add('correct');$$('.choice-btn').forEach(v=>v.disabled=true);$('.feedback').classList.add('show');completeCurrent();updateV2Chrome();if(state.lesson===6)setTimeout(renderV2,500)}else{b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),350)}});
 const exit=$('#exitBtn');if(exit)exit.onclick=()=>{play('click');if(window.SCORM)SCORM.complete();toast('Course completion recorded');setTimeout(()=>{try{window.close()}catch(e){}},500)};
 updateV2Chrome();els.main.focus();window.scrollTo(0,0);
}

function updateV2Chrome(){
 const atActivity=state.screen===4,atScenario=state.screen===5,lessonDone=state.completed.includes(state.lesson);
 els.back.disabled=state.lesson===0&&state.screen===0;
 els.next.disabled=(atActivity&&!allCardsSeen(state.lesson))||(atScenario&&!lessonDone);
 els.next.textContent=atScenario?(state.lesson===lessons.length-1?'Course Complete':'Next Lesson →'):'Next →';
 els.indicator.textContent=`Screen ${lessonProgress()}`;
 const total=lessons.length*screenCount(),completeScreens=state.lesson*screenCount()+state.screen+(lessonDone&&state.lesson===6?1:0),p=Math.round(completeScreens/total*100);
 els.bar.style.width=p+'%';els.pct.textContent=p+'%';
 els.status.textContent=lessonDone?'Completed':sectionLabel();
 renderNavV2();
}

function renderNavV2(){els.nav.innerHTML=lessons.map((l,i)=>`<button class="lesson-link ${i===state.lesson?'active':''} ${state.completed.includes(i)?'complete':''}" data-i="${i}" ${isUnlocked(i)?'':'disabled'}><span class="lesson-num">${state.completed.includes(i)?'✓':i+1}</span><span class="lesson-copy">${esc(l.title)}</span><span class="lock">${isUnlocked(i)?'':'🔒'}</span></button>`).join('');$$('.lesson-link').forEach(b=>b.onclick=()=>{play('click');state.lesson=+b.dataset.i;state.screen=0;renderV2();save();if(innerWidth<900)els.side.classList.remove('mobile-open')})}

$('#startBtn').onclick=()=>{state.started=true;state.lesson=0;state.screen=0;els.start.classList.add('hidden');els.shell.classList.remove('hidden');play('menu');renderV2();save()};
$('#resumeBtn').onclick=()=>{state.started=true;els.start.classList.add('hidden');els.shell.classList.remove('hidden');play('menu');renderV2();save()};
els.back.onclick=()=>{play('click');if(state.screen>0)setScreen(state.screen-1);else if(state.lesson>0){state.lesson--;state.screen=5;renderV2();save()}};
els.next.onclick=()=>{if(els.next.disabled)return;play('click');if(state.screen<5)setScreen(state.screen+1);else if(state.lesson<lessons.length-1){state.lesson++;state.screen=0;renderV2();save()}else toast('Course complete. Select Exit Course below.')};
