// Fraud 101 course content and standalone six-lesson configuration.
(function () {
  const courseLessons = [
    {
      title: 'Understanding Advanced Fraud Risk',
      purpose: 'Evaluate fraud as connected activity across the customer journey and make explicit risk trade-offs.',
      objectives: ['Map fraud exposure across the complete customer journey.','Distinguish an event, pattern, campaign, and network.','Build a testable fraud hypothesis using supporting and contradicting evidence.'],
      intro: 'A transaction may be only one visible stage in a larger fraud sequence. Advanced fraud teams connect account, payment, fulfillment, support, refund, and dispute activity instead of reviewing each event in isolation.',
      activityTitle: 'Map the Developing Attack', activityIntro: 'Select each stage to see how a seemingly ordinary event can contribute to a coordinated fraud sequence.',
      cards: [
        ['Account access','A known account signs in from a new device.','Check authentication, recovery, device continuity, and recent profile changes before treating the login as an isolated event.'],
        ['Low-value order','The account places a small order that clears existing rules.','Consider whether the order is testing a card, address, fulfillment method, or merchant threshold.'],
        ['Address change','Delivery moves to a new address shortly after purchase.','Compare timing, account history, linked accounts, and whether the change bypassed normal confirmation.'],
        ['Higher-value order','The same account quickly increases order value.','Test whether the earlier activity established trust that is now being exploited.'],
        ['Refund request','Support receives a refund request after delivery.','Link the claim to delivery evidence, account changes, support language, and related claims.'],
        ['Network view','Other accounts share devices, addresses, or payment instruments.','Assess the strength, timing, density, and business plausibility of the links before concluding they form a fraud network.']
      ],
      key: 'Advanced fraud analysis connects events across time, systems, and entities before deciding what the activity means.',
      scenario: {intro:'You are reviewing an emerging pattern for an online electronics merchant.',title:'Small Signals, One Developing Campaign',body:['Low-value orders, delivery-address changes, and refund requests have each increased slightly. None of the individual metrics exceeds an alert threshold.','Several affected accounts were created or recovered within the same week, selected similar high-resale products, and contacted support using closely related language.'],question:'What is the best next step?',choices:['Raise every individual alert threshold so only larger changes reach the fraud team.','Connect the accounts, devices, addresses, products, and support activity, then test a campaign hypothesis.','Decline every order involving an address change until the refund rate returns to normal.'],correct:1,feedback:'Correct. The linked timing and behavior justify a campaign-level investigation. A testable hypothesis should include supporting evidence, contradicting evidence, required data, and expected customer impact.'}
    },
    {
      title: 'Coordinated Attacks, Automation, and AI-Enabled Fraud',
      purpose: 'Recognize how sophisticated attacks prepare, scale, adapt, and monetize activity using automation and AI.',
      objectives: ['Break attacks into preparation, execution, monetization, and concealment stages.','Identify coordinated and automated activity using multi-dimensional velocity.','Recommend layered controls for adaptive bots, synthetic identities, deepfakes, and social engineering.'],
      intro: 'AI often makes established attacks faster, cheaper, more personalized, and more convincing. Effective detection focuses on behavior, relationships, and verification discipline rather than grammar, appearance, or one technical signal.',
      activityTitle: 'Investigate the Fraud Network', activityIntro: 'Select each network signal to see what it contributes and what additional context is needed.',
      cards: [
        ['Shared device traits','Many accounts present the same unusual device configuration.','A strong technical link, especially when combined with coordinated timing or shared value destinations.'],
        ['Common address','Several customers use one freight-forwarding address.','Potentially meaningful, but legitimate customers may share forwarding services. Add payment, behavior, and claim context.'],
        ['Repeated contact structure','Emails and phone numbers follow the same generated pattern.','Supports coordinated account creation when timing, device, promotion, or payment evidence also aligns.'],
        ['Polished recovery messages','Support receives convincing, personalized requests.','Writing quality does not establish legitimacy. Verify through trusted channels and account history.'],
        ['Diverse IP addresses','Requests rotate through many networks.','Distribution can hide velocity. Evaluate devices, sessions, identities, payments, and destinations together.'],
        ['Linked beneficiaries','Different accounts send value to the same payout or resale destination.','A high-value connection that may reveal the monetization point of a coordinated network.']
      ],
      key: 'A single shared attribute rarely proves coordination. Evaluate the strength, timing, density, and plausibility of the relationships.',
      scenario: {intro:'You lead fraud response for a merchant experiencing unusual account recovery activity.',title:'The Convincing Recovery Surge',body:['Support receives polished recovery requests with realistic identity documents. Each recovered account makes one low-volume purchase from a different device.','The requests share contact patterns, recovery timing, and delivery destinations. Several identity images contain subtle inconsistencies.'],question:'What response best addresses the risk?',choices:['Require trusted-channel verification, restrict sensitive actions after recovery, and investigate the linked account network.','Approve the recoveries because the documents and messages appear professional and each account has low volume.','Block every customer using a new device because diverse devices are the strongest proof of automation.'],correct:0,feedback:'Correct. The combination suggests coordinated, AI-assisted activity. Layered verification, temporary restrictions, and network investigation address the attack without treating one signal as conclusive.'}
    },
    {
      title: 'Identity, Account Security, and Payment Authentication',
      purpose: 'Combine identity proofing, authentication, recovery, authorization, and payment decisions into a layered strategy.',
      objectives: ['Distinguish identity proofing, authentication, authorization, and recovery.','Apply risk-based step-up controls to sensitive actions.','Interpret merchant screening, cardholder authentication, and issuer authorization as separate decisions.'],
      intro: 'Strong login authentication can coexist with weak account recovery or support procedures. Attackers target the easiest path, so every sensitive action must be evaluated in context.',
      activityTitle: 'Choose the Right Authentication Response', activityIntro: 'Select each action to see the proportionate response supported by its sensitivity and surrounding risk.',
      cards: [
        ['Routine purchase','Known device, stable behavior, established address, and normal value.','Allow with normal monitoring when no material risk change is present.'],
        ['New payment method','A familiar customer adds a card from a new device.','Consider reauthentication or passkey confirmation before storing or using the new method.'],
        ['Account recovery','A customer cannot use the standard authenticator.','Prefer an existing trusted device or channel, notify established contacts, and restrict sensitive follow-on activity.'],
        ['Phone-number change','A recovered account immediately replaces its contact number.','Apply a cooling-off period or stronger verification before the new number can approve high-risk actions.'],
        ['High-value stored value','A session redeems loyalty value after a password reset.','Require strong step-up and review the full recovery and session sequence.'],
        ['Video support request','A convincing caller asks an agent to remove a hold.','Do not treat video presence as proof. Verify through independent account, device, and trusted-channel evidence.']
      ],
      key: 'Authentication proves control of an authenticator, not that every requested action is legitimate or authorized.',
      scenario: {intro:'You are reviewing a high-risk order after account recovery.',title:'A Familiar Customer, an Unfamiliar Recovery',body:['A long-standing account is recovered from a new device. The phone number changes, and a high-value order is placed with a stored payment method.','Support receives a convincing video request to remove the fulfillment hold. Issuer authorization and payment authentication both succeed.'],question:'What is the most appropriate response?',choices:['Release the order because the payment decisions succeeded and the customer appeared on video.','Cancel the account permanently because any recovery from a new device proves takeover.','Maintain the hold, verify through an established channel, review recovery evidence, and restrict sensitive changes until risk is resolved.'],correct:2,feedback:'Correct. Payment approval and realistic video do not resolve the recovery risk. Independent trusted-channel verification and temporary restrictions are proportionate to the sequence.'}
    },
    {
      title: 'Fraud Decisioning, Models, and Investigations',
      purpose: 'Use rules, models, anomaly detection, graph analysis, testing, and human judgment responsibly.',
      objectives: ['Explain the distinct roles of rules, supervised models, anomaly detection, graph analysis, and review.','Recognize label-quality, drift, explainability, and bias risks.','Test controls safely and conduct evidence-based investigations.'],
      intro: 'Modern fraud decisions combine different tools because each answers a different question. The goal is not maximum automation. It is consistent, accountable decisions supported by reliable evidence and measured outcomes.',
      activityTitle: 'Select the Safe Testing Method', activityIntro: 'Select each method to see when it helps teams evaluate a new rule or model before broad deployment.',
      cards: [
        ['Shadow mode','Score live activity without changing customer outcomes.','Use it to measure likely decisions and investigate surprises before the control affects customers.'],
        ['Champion and challenger','Compare the current strategy with a proposed alternative.','Use consistent populations and mature outcomes to evaluate incremental value.'],
        ['Limited rollout','Deploy to a defined percentage, market, product, or risk band.','Limit exposure while monitoring fraud, approvals, friction, workload, and segment impact.'],
        ['Backtesting','Apply a proposed strategy to historical data.','Prevent data leakage and exclude transactions whose fraud outcomes were not yet mature.'],
        ['Manual escalation','Send ambiguous, high-impact cases to trained analysts.','Provide source evidence, a clear question, and consistent documentation requirements.'],
        ['Rollback criteria','Define when the team will disable or reverse the change.','Set thresholds before launch so poor performance can be addressed without debate during an incident.']
      ],
      key: 'Fraud models and AI support decisions; they do not remove accountability for evidence quality, customer impact, or consequential outcomes.',
      scenario: {intro:'You are evaluating an anomaly model before broader deployment.',title:'The Suspicious Employer Network',body:['An AI-assisted model identifies a new cluster of accounts sharing network infrastructure and similar login times. The model recommends blocking the cluster.','Investigation shows many accounts belong to employees using a shared corporate network. A smaller subset also shares payment instruments and delivery locations with confirmed fraud.'],question:'What should the team do?',choices:['Block the full cluster because the model detected a statistically unusual network.','Separate weak shared-network links from stronger fraud links, test refined features in shadow mode, and escalate the high-confidence subset.','Ignore the cluster because any legitimate accounts make network analysis unsuitable for decisioning.'],correct:1,feedback:'Correct. The team should remove the biased or weak feature, preserve stronger relationships, and test the revised strategy before broad customer impact.'}
    },
    {
      title: 'First-Party Misuse, Policy Abuse, and Fraud Performance',
      purpose: 'Classify customer-originated loss accurately and evaluate controls using balanced business outcomes.',
      objectives: ['Distinguish third-party fraud, first-party misuse, policy abuse, and legitimate disputes.','Choose proportionate responses for repeat or organized abuse.','Measure false positives, false negatives, revenue, customer, and operational effects.'],
      intro: 'Loss classification matters because the evidence, controls, customer treatment, and recovery options differ. Legitimate delivery failures and merchant errors can resemble abuse, while repeat misuse can resemble ordinary service activity.',
      activityTitle: 'Interpret the Complete Dashboard', activityIntro: 'Select each measure to see why a fraud control should be evaluated beyond reported fraud alone.',
      cards: [
        ['Fraud loss','Confirmed unauthorized loss decreased after the control.','Important, but verify outcome maturity and whether loss moved to refunds, promotions, or another channel.'],
        ['Approval rate','Fewer legitimate orders were approved.','Estimate lost margin, customer value, and whether the decline is concentrated in particular segments.'],
        ['Manual review','Review volume doubled.','Include staffing cost, queue delay, decision quality, and capacity risk in the control assessment.'],
        ['Customer contacts','Complaints and repeat contacts increased.','Investigate confusing messages, delayed fulfillment, inaccessible verification, and incorrect challenges.'],
        ['Refund loss','Refund and return losses increased.','Fraud may have shifted post-purchase or the control may be misclassifying service failures.'],
        ['False positives','Legitimate customers were blocked or delayed.','Measure the financial and customer cost alongside fraud caught and false negatives.']
      ],
      key: 'A control is valuable only when its fraud benefit exceeds its revenue, customer, operational, and displacement costs.',
      scenario: {intro:'You are reviewing a disputed-order case involving a long-standing customer.',title:'The Loyal Customer with Linked Abuse',body:['A high-value customer disputes several delivered orders after years of legitimate activity. The account shares a device with two promotion-abuse accounts.','Delivery evidence is strong, but billing descriptors were recently changed and support records show earlier customer confusion.'],question:'What is the best next step?',choices:['Separate unauthorized-use evidence from policy-abuse and service evidence, then choose a proportionate response based on the verified facts.','Classify the case as organized abuse because the shared device conclusively links all three customers.','Approve every dispute because long account tenure outweighs delivery and network evidence.'],correct:0,feedback:'Correct. The shared device is relevant but not conclusive. Classification should consider authorization, customer participation, delivery, merchant communication, linked behavior, and contradicting evidence.'}
    },
    {
      title: 'Fraud Operations, Incident Response, and Capstone',
      purpose: 'Coordinate cross-functional fraud operations, respond to concentrated attacks, and govern durable control changes.',
      objectives: ['Define incident levels, owners, escalation paths, and containment actions.','Govern emergency controls, models, AI, vendors, and post-incident changes.','Build a complete response to a multi-stage, AI-enabled fraud campaign.'],
      intro: 'A mature fraud program defines roles and escalation paths before an incident. Fast containment matters, but teams must also preserve evidence, protect customers, monitor displacement, and validate permanent changes.',
      activityTitle: 'Build the Incident Response', activityIntro: 'Select each response stage to review the decision and evidence it should produce.',
      cards: [
        ['1. Detect and validate','Confirm the anomaly and rule out data, reporting, or operational errors.','Record the trigger, baseline, affected population, and initial confidence.'],
        ['2. Assign ownership','Name an incident owner and involved functions.','Define decision rights, communication paths, and escalation level.'],
        ['3. Estimate exposure','Identify affected journeys, products, systems, customers, and value.','Estimate current loss, potential loss, customer impact, and operational capacity.'],
        ['4. Contain proportionately','Limit the immediate attack without stopping all legitimate activity.','Target the affected endpoint, network, product, payment path, fulfillment method, or promotion.'],
        ['5. Preserve and communicate','Protect source evidence and notify the teams that must act.','Keep decisions traceable and avoid sharing sensitive information beyond operational need.'],
        ['6. Learn and improve','Monitor displacement, implement durable controls, and complete a review.','Assign every action an owner, due date, success measure, and reassessment date.']
      ],
      key: 'Incident response succeeds when teams contain the attack, preserve evidence, protect legitimate customers, and turn lessons into validated controls.',
      scenario: {intro:'You are leading the response to a coordinated promotion attack.',title:'The Promotion Attack Across the Customer Journey',body:['New-account creation and login failures triple during a high-demand promotion. Accounts share device traits, cards, and delivery destinations while staying below review thresholds.','Support receives polished address-change requests with realistic voice clips. Refund claims begin after delivery; some customers deny creating accounts while others admit ordering but deny promotion abuse.'],question:'What is the best immediate response?',choices:['Pause the entire commerce site until every account and refund can be investigated.','Continue normal operations because each order remains below the manual-review threshold.','Target the linked network and affected promotion, strengthen recovery and fulfillment controls, preserve evidence, and assign a cross-functional incident owner.'],correct:2,feedback:'Correct. Targeted containment addresses the concentrated attack while preserving legitimate sales. The response should cover account access, payment, fulfillment, support, refunds, network analysis, communication, and displacement monitoring.'}
    }
  ];

  const courseScreens = [
    {whyTitle:'Why Transaction-Only Review Creates Blind Spots',why:['Fraud develops across multiple customer and operational stages. Reviewing only the final order can miss the testing, account changes, fulfillment manipulation, and post-purchase activity that made the loss possible.','Risk appetite makes trade-offs explicit across fraud loss, approval, friction, review capacity, operational cost, and customer value.'],conceptsTitle:'Four Levels of Connected Fraud',conceptsIntro:'Use these terms to describe the scale and coordination of the activity being investigated.',concepts:[['Fraud event','One suspicious login, order, refund, account change, or payout request.'],['Fraud pattern','Repeated behavior sharing attributes across events or entities.'],['Fraud campaign','A coordinated series targeting a product, promotion, process, or vulnerability.'],['Fraud network','Linked accounts, devices, identities, payments, addresses, or beneficiaries working together.']],applyTitle:'Build a Testable Fraud Hypothesis',applyIntro:'Move from suspicion to a structured explanation the team can test.',apply:['State the suspected pattern and affected journey.','List supporting and contradicting signals.','Identify the required data and linked entities.','Estimate exposure and legitimate-customer impact.','Select a safe test or temporary control.','Define the measures that will confirm or disprove the hypothesis.']},
    {whyTitle:'AI Changes the Scale and Quality of Familiar Attacks',why:['Generative AI can improve phishing, identity records, scripts, translations, and long-running conversations. Automation can vary timing and navigation to evade static controls.','Defenses should focus on trusted verification, behavior, devices, payments, velocity, and network relationships rather than surface appearance.'],conceptsTitle:'The Advanced Fraud Attack Chain',conceptsIntro:'Follow how sophisticated operations prepare, execute, monetize, and adapt.',concepts:[['1. Reconnaissance','Research products, controls, support procedures, limits, and fulfillment.'],['2. Resource acquisition','Obtain credentials, identities, proxies, bots, mules, and resale services.'],['3. Testing and execution','Probe controls, then increase value, volume, or complexity.'],['4. Monetization','Extract value through goods, stored value, refunds, payouts, or resale.'],['5. Concealment and adaptation','Change infrastructure, identities, behavior, products, and timing after controls respond.']],applyTitle:'Use Multi-Dimensional Velocity',applyIntro:'Measure coordinated activity across more than one identifier.',apply:['Track accounts per device and devices per account.','Measure payment, promotion, and contact reuse.','Connect addresses, pickup points, and beneficiaries.','Compare timing and action sequences across sessions.','Separate strong links from common legitimate infrastructure.','Apply progressive friction and targeted containment to the combined risk.']},
    {whyTitle:'Attackers Target the Weakest Identity Path',why:['Strong authentication can be undermined by weak recovery, recently changed contact information, or support overrides. Sensitive actions require context beyond a successful login.','A successful issuer authorization does not prove that an account, customer, or order is legitimate.'],conceptsTitle:'Four Separate Identity Decisions',conceptsIntro:'Keep these decisions distinct so one successful check does not substitute for another.',concepts:[['Identity proofing','Who is attempting to create or control the account?'],['Authentication','Can the user demonstrate control of an approved authenticator?'],['Authorization','May the authenticated user perform this action?'],['Account recovery','How is access restored when the standard authenticator is unavailable?'],['Payment decisions','How do merchant screening, cardholder authentication, and issuer authorization contribute different evidence?']],applyTitle:'Protect High-Risk Recovery and Account Changes',applyIntro:'Use a sequence that relies on trusted continuity and proportionate restrictions.',apply:['Score the recovery request and surrounding session.','Verify through an existing trusted device or channel where possible.','Notify established contact methods.','Delay or restrict sensitive changes when risk is elevated.','Review linked sessions, devices, payments, and account changes.','Escalate suspicious attempts and preserve source evidence.']},
    {whyTitle:'Every Decisioning Tool Has a Different Role',why:['Rules provide transparent controls for known conditions. Models estimate similarity to historical outcomes. Anomaly detection identifies unusual behavior. Graph analysis reveals relationships. Analysts add context where errors are costly.','Weak labels, immature outcomes, drift, and bias can make a technically accurate system produce poor business decisions.'],conceptsTitle:'A Layered Decision Framework',conceptsIntro:'Combine controls in a deliberate order and define what each layer contributes.',concepts:[['Security and compliance','Enforce non-negotiable access, data, and policy requirements.'],['Known network and bot controls','Disrupt confirmed infrastructure, concentrated attacks, and automated abuse.'],['Fraud and authentication decisions','Combine risk scores, context, and appropriate step-up.'],['Manual review and fulfillment','Route ambiguous cases and restrict value delivery when justified.'],['Post-transaction monitoring','Use mature outcomes to tune controls and identify displacement.']],applyTitle:'Conduct an Evidence-Based Investigation',applyIntro:'Document enough information for another trained reviewer to understand and challenge the conclusion.',apply:['Record the triggering activity and fraud hypothesis.','Separate supporting from contradicting evidence.','Identify linked entities and estimate exposure.','State the recommended action and confidence level.','Document required follow-up and source evidence.','Record the final mature outcome and feed it back into the strategy.']},
    {whyTitle:'Similar Losses Require Different Responses',why:['Third-party fraud, first-party misuse, policy abuse, and legitimate disputes can produce similar claims but involve different customer participation and merchant obligations.','Poor classification can harm legitimate customers, hide service failures, and train models on inaccurate outcomes.'],conceptsTitle:'Classify the Loss Before Choosing the Control',conceptsIntro:'Use customer participation, authorization, merchant performance, and policy evidence to distinguish the loss type.',concepts:[['Third-party fraud','An unauthorized person uses another person’s account, identity, or payment method.'],['First-party misuse','The legitimate customer participates in the transaction and later denies or disputes it.'],['Policy abuse','A customer intentionally exploits merchant policies without necessarily claiming unauthorized payment.'],['Legitimate dispute','A valid issue involves delivery, billing, cancellation, quality, or merchant communication.']],applyTitle:'Evaluate the Full Value of a Control',applyIntro:'Measure both fraud benefit and the costs imposed elsewhere in the business.',apply:['Confirm outcomes are mature enough to evaluate.','Measure fraud caught and fraudulent activity missed.','Measure approval, conversion, and legitimate revenue affected.','Measure customer friction, complaints, and repeat contacts.','Measure review, authentication, fulfillment, and support cost.','Check whether loss shifted to another channel, policy, or customer segment.']},
    {whyTitle:'Fraud Incidents Require Prepared Cross-Functional Action',why:['Fraud strategy, review, payments, security, service, fulfillment, finance, product, engineering, legal, and data teams may all hold part of the response.','Emergency controls can create lasting customer harm if they remain active without testing, monitoring, ownership, and expiration.'],conceptsTitle:'Three Incident Levels',conceptsIntro:'Choose an operating level based on financial, operational, customer, legal, and reputational exposure.',concepts:[['Level 1: Normal variation','Handle through routine monitoring, investigation, and tuning.'],['Level 2: Concentrated attack','Use targeted controls and coordinated cross-team response.'],['Level 3: Major incident','Activate formal incident management for significant exposure or customer harm.']],applyTitle:'Govern Durable Control Changes',applyIntro:'Require every significant rule, model, AI, vendor, and policy change to have clear evidence and ownership.',apply:['Define the business problem and testable hypothesis.','Name the control owner and approval authority.','Document data, features, expected benefit, and customer impact.','Define testing, monitoring, and human oversight.','Set rollback criteria and an expiration or review date.','Verify vendor data use, outages, explainability, retention, and exit options.']}
  ];

  const courseExtras = [
    {title:'Risk Appetite Is a Business Decision',intro:'The objective is not zero fraud at any cost. A mature program defines acceptable exposure while protecting approvals, customer experience, operational capacity, and commercial goals.',paras:['Tolerance may differ by product, market, payment method, value, customer tenure, delivery method, and resale potential. Document who can approve those differences and how performance will be reviewed.'],takeaway:'Use risk appetite to make trade-offs explicit before an incident or control change.'},
    {title:'AI-Generated Evidence Still Requires Independent Verification',intro:'Realistic documents, audio, video, and messages can contribute evidence, but none should be treated as proof by appearance alone.',paras:['For sensitive recovery or payment actions, combine trusted-device continuity, cryptographic authentication, account history, verified contact channels, behavior, and network evidence.'],takeaway:'Verify unusual requests through an established independent channel.'},
    {title:'Interpret Payment Decisions Together',intro:'Merchant fraud screening, cardholder authentication, and issuer authorization use overlapping but different data. One successful result cannot answer every risk question.',paras:['Authentication may be less effective when a real customer is manipulated, the account and authentication channel are both compromised, or the loss is policy abuse rather than unauthorized payment.'],takeaway:'Payment approval confirms a payment-system decision, not the legitimacy of the entire customer journey.'},
    {title:'Label Quality Shapes Model Quality',intro:'Confirmed fraud, disputes, refunds, authentication failures, manual declines, and account closures are not equivalent labels.',paras:['If every analyst decline is treated as confirmed fraud, a model may learn historical assumptions instead of verified outcomes. Evaluate recent strategies only after outcomes have matured.'],takeaway:'Trace every training and evaluation label to its definition, source, timing, and confidence.'},
    {title:'Look for Fraud Displacement',intro:'A successful control may push attackers to another product, fulfillment method, promotion, support process, refund path, or payment method.',paras:['Review performance by segment and root cause so an overall improvement does not hide concentrated loss or customer harm.'],takeaway:'Measure the whole customer and loss journey, not only the point where a control was added.'},
    {title:'Capstone Response Priorities',intro:'The coordinated promotion scenario combines account takeover, payment fraud, promotion abuse, AI-enabled support manipulation, synthetic identity evidence, first-party misuse, and legitimate customers.',paras:['A strong response separates confirmed, suspected, and inconclusive activity; contains the highest-risk paths; preserves evidence; assigns owners; and defines measures, rollback criteria, and post-incident actions.'],takeaway:'Contain proportionately, investigate systematically, and make every durable change testable.'}
  ];

  const courseChecks = [
    {type:'choice',prompt:'Which evidence most strongly supports treating several small changes as a developing campaign?',choices:['Each metric remains below its individual alert threshold.','The events share timing, entities, products, and support behavior across the journey.','One affected order used a new delivery address.'],correct:1,feedback:'Correct. Connected timing and relationships across stages support a campaign hypothesis more strongly than one isolated event.'},
    {type:'match',prompt:'Match each attack stage to the example.',pairs:[['Researching merchant limits','Reconnaissance'],['Increasing order value after testing','Execution'],['Changing devices after controls respond','Adaptation']],options:['Execution','Adaptation','Reconnaissance'],feedback:'Correct. Preparation, execution, and adaptation describe different stages of a sophisticated attack.'},
    {type:'choice',prompt:'A recovered account passes issuer authorization and submits a convincing support video. What evidence is still needed?',choices:['Independent trusted-channel and account-continuity evidence.','Only a higher payment authorization amount.','No additional evidence because both checks succeeded.'],correct:0,feedback:'Correct. Neither issuer approval nor realistic video resolves whether recovery and sensitive changes are legitimate.'},
    {type:'choice',prompt:'What is the safest first use of a high-impact anomaly model with uncertain features?',choices:['Deploy it globally and reverse incorrect blocks later.','Run it in shadow mode and investigate outcomes before customer impact.','Treat every anomaly as confirmed fraud for model training.'],correct:1,feedback:'Correct. Shadow mode supports measurement and feature review before consequential decisions.'},
    {type:'choice',prompt:'Why should a merchant separate policy abuse from a legitimate dispute?',choices:['The evidence, customer treatment, controls, and remedies may differ.','Every legitimate dispute should be handled as unauthorized payment.','Policy abuse always requires permanently closing the customer account.'],correct:0,feedback:'Correct. Accurate classification supports proportionate controls and fair customer treatment.'},
    {type:'match',prompt:'Match each response stage to its purpose.',pairs:[['Confirm the anomaly','Validate'],['Limit the immediate attack','Contain'],['Assign permanent actions and measures','Improve']],options:['Contain','Improve','Validate'],feedback:'Correct. Validation, containment, and durable improvement serve different incident-response purposes.'}
  ];

  const courseReviews = courseLessons.map((lesson, i) => ({
    summary: lesson.key,
    takeaways: [
      [lesson.objectives[0], 'Apply this capability using connected evidence and the full customer journey.'],
      [lesson.objectives[1], 'Use clear definitions and proportionate responses rather than one-signal conclusions.'],
      [lesson.objectives[2], 'Document ownership, customer impact, testing, and outcome measures.']
    ],
    next: i < 5 ? `In the next lesson, you will explore ${courseLessons[i + 1].title.toLowerCase()}.` : 'Next, review the course-wide advanced fraud framework and prepare for the final exam.'
  }));

  const courseExam = [
    {type:'single',prompt:'Several small risk metrics rise together across account recovery, orders, and refunds. What is the best first action?',options:['Connect the activity and test a campaign hypothesis.','Increase each alert threshold independently.','Decline every account involved in one metric.'],correct:0},
    {type:'single',prompt:'A shared corporate network links legitimate and fraudulent accounts. What should the team do?',options:['Block the full network because it contains fraud.','Ignore every network relationship as coincidental.','Separate weak infrastructure links from stronger entity relationships.'],correct:2},
    {type:'single',prompt:'A recovered account receives issuer approval for a high-value order. What does that prove?',options:['The issuer approved the payment request, not the entire recovery journey.','The account recovery and support override were legitimate.','The customer personally authorized every account change.'],correct:0},
    {type:'truefalse',prompt:'A fraud event and a fraud campaign describe the same level of activity.',options:['True','False'],correct:1},
    {type:'multi',prompt:'Which elements belong in a testable fraud hypothesis? Select four.',options:['Supporting signals.','Contradicting signals.','Required data.','Expected customer impact.','A guarantee that the hypothesis is correct.'],correct:[0,1,2,3]},
    {type:'truefalse',prompt:'Polished writing is sufficient evidence that a recovery request is legitimate.',options:['True','False'],correct:1},
    {type:'multi',prompt:'Which signals help identify coordinated automation? Select four.',options:['Device relationships.','Payment and beneficiary reuse.','Cross-entity timing.','Shared action sequences.','Grammar quality by itself.'],correct:[0,1,2,3]},
    {type:'truefalse',prompt:'Distributed attacks can remain below single-entity velocity thresholds.',options:['True','False'],correct:0},
    {type:'multi',prompt:'Which controls support high-risk account recovery? Select four.',options:['Trusted-channel verification.','Established-contact notification.','Temporary sensitive-action restrictions.','Linked-session review.','Immediate removal of every hold.'],correct:[0,1,2,3]},
    {type:'truefalse',prompt:'A passkey removes the need to secure account recovery and support procedures.',options:['True','False'],correct:1},
    {type:'multi',prompt:'Which are separate payment or fraud decisions? Select three.',options:['Merchant fraud screening.','Cardholder authentication.','Issuer authorization.','Final proof that the purchase is legitimate.'],correct:[0,1,2]},
    {type:'truefalse',prompt:'Shadow mode allows a team to evaluate a control without changing customer decisions.',options:['True','False'],correct:0},
    {type:'multi',prompt:'Which risks should be reviewed when using AI in fraud prevention? Select four.',options:['Biased or weak labels.','Model drift.','False positives and uneven segment impact.','Overreliance on generated summaries.','Guaranteed elimination of human accountability.'],correct:[0,1,2,3]},
    {type:'truefalse',prompt:'A manual-review decline should always be used as a confirmed-fraud label.',options:['True','False'],correct:1},
    {type:'multi',prompt:'Which records belong in a structured investigation? Select four.',options:['Fraud hypothesis.','Supporting and contradicting evidence.','Linked entities and exposure.','Confidence and follow-up.','Only the final decision code.'],correct:[0,1,2,3]},
    {type:'truefalse',prompt:'First-party misuse and a legitimate dispute may require different evidence and remedies.',options:['True','False'],correct:0},
    {type:'multi',prompt:'Which measures belong in a balanced control evaluation? Select four.',options:['Fraud loss.','Approval and legitimate revenue.','Customer friction.','Operational workload.','Only the number of blocked transactions.'],correct:[0,1,2,3]},
    {type:'truefalse',prompt:'A reduction in reported fraud can hide displacement into refunds or another channel.',options:['True','False'],correct:0},
    {type:'multi',prompt:'Which actions belong in incident response? Select four.',options:['Assign an owner.','Estimate exposure.','Contain proportionately.','Preserve evidence and monitor displacement.','Leave emergency controls active indefinitely.'],correct:[0,1,2,3]},
    {type:'truefalse',prompt:'Durable fraud-control changes should include monitoring, rollback criteria, and a review date.',options:['True','False'],correct:0}
  ];

  lessons.splice(0, lessons.length, ...courseLessons, {title:'Review and Resources',purpose:'Consolidate the advanced fraud framework and prepare for the final exam.',objectives:['Summarize the six advanced fraud capabilities.','Identify practical resources for continued implementation.','Prepare to apply the framework in the final exam.'],intro:'This final lesson brings the course together.',cards:[],key:'Advanced fraud management connects evidence, decisions, owners, customer impact, and measured outcomes.'});
  screenContent.splice(0, screenContent.length, ...courseScreens);
  extraContent.splice(0, extraContent.length, ...courseExtras);
  knowledgeChecks.splice(0, knowledgeChecks.length, ...courseChecks);
  lessonReviews.splice(0, lessonReviews.length, ...courseReviews);
  examQuestions.splice(0, examQuestions.length, ...courseExam);

  additionalScenarioAudio[0] = {intro:'assets/lesson-1-scenario-intro.mp3',question:'assets/lesson-1-scenario-question.mp3',correct:'assets/lesson-1-scenario-correct.mp3',incorrect:'assets/lesson-1-scenario-incorrect.mp3'};
  additionalScenarioAudio[1] = {intro:'assets/lesson-2-scenario-intro.mp3',question:'assets/lesson-2-scenario-question.mp3',correct:'assets/lesson-2-scenario-correct.mp3',incorrect:'assets/lesson-2-scenario-incorrect.mp3'};
  additionalScenarioAudio[2] = {intro:'assets/lesson-3-scenario-intro.mp3',question:'assets/lesson-3-scenario-question.mp3',correct:'assets/lesson-3-scenario-correct.mp3',incorrect:'assets/lesson-3-scenario-incorrect.mp3'};
  additionalScenarioAudio[3] = {intro:'assets/lesson-4-scenario-intro.mp3',question:'assets/lesson-4-scenario-question.mp3',correct:'assets/lesson-4-scenario-correct.mp3',incorrect:'assets/lesson-4-scenario-incorrect.mp3'};
  additionalScenarioAudio[4] = {intro:'assets/lesson-5-scenario-intro.mp3',question:'assets/lesson-5-scenario-question.mp3',correct:'assets/lesson-5-scenario-correct.mp3',incorrect:'assets/lesson-5-scenario-incorrect.mp3'};
  additionalScenarioAudio[5] = {intro:'assets/lesson-6-scenario-intro.mp3',question:'assets/lesson-6-scenario-question.mp3',correct:'assets/lesson-6-scenario-correct.mp3',incorrect:'assets/lesson-6-scenario-incorrect.mp3'};
  lessonOneScenarioAudio.intro = additionalScenarioAudio[0].intro;
  lessonOneScenarioAudio.question = additionalScenarioAudio[0].question;
  lessonOneScenarioAudio.correct = additionalScenarioAudio[0].correct;
  lessonOneScenarioAudio.incorrect = additionalScenarioAudio[0].incorrect;

  document.title = 'Fraud 101';
  const courseTitle = document.getElementById('courseTitle'); if (courseTitle) courseTitle.textContent = 'Fraud 101';
  const sideTitle = document.querySelector('.side-course-title'); if (sideTitle) sideTitle.textContent = 'Fraud 101';

  renderCourseOverview = function () {
    stopScenarioAudio(); state.onOverview = true;
    els.kicker.textContent = 'Course Overview'; els.title.textContent = 'Fraud 101'; els.status.textContent = 'Getting started';
    const topics = courseLessons.map((l,i)=>[String(i+1).padStart(2,'0'),l.title,l.purpose]);
    els.main.innerHTML = `<section class="screen-panel course-overview-screen"><span class="screen-eyebrow">Course Overview</span><h3>Manage Fraud as a Connected Business Risk</h3><p class="overview-lead">This advanced course is designed for experienced fraud, payments, risk, and eCommerce professionals. It builds on Fraud Essentials and focuses on coordinated attacks, identity and payment security, decisioning, investigations, performance, and incident response.</p><div class="overview-section"><h4>What This Course Covers</h4><div class="overview-topic-grid">${topics.map(t=>`<article><span>${t[0]}</span><h5>${esc(t[1])}</h5><p>${esc(t[2])}</p></article>`).join('')}</div></div><div class="overview-outcomes"><h4>By the End of This Course, You Will Be Able To:</h4><ul><li>Analyze fraud across the complete customer journey.</li><li>Identify coordinated, automated, and AI-enabled attacks.</li><li>Apply layered identity, authentication, payment, and account controls.</li><li>Use rules, models, networks, testing, and investigations responsibly.</li><li>Distinguish fraud, misuse, abuse, and legitimate disputes.</li><li>Lead incident response and continuous improvement using balanced measures.</li></ul></div></section>`;
    els.back.disabled=true; els.next.disabled=false; els.next.textContent=hasMeaningfulCourseProgress()?'Continue Course →':'Begin Lesson 1 →'; els.indicator.textContent='Course Overview'; els.bar.style.width='0%'; els.pct.textContent='0%'; renderOverviewNav(); els.main.focus(); window.scrollTo(0,0); save();
  };

  renderReviewScreen = function () {
    const skills=['Analyze connected fraud across the customer journey.','Detect coordinated, automated, and AI-enabled attacks.','Protect identity, accounts, recovery, and payments.','Use fraud decisioning and AI with accountable testing and oversight.','Classify loss accurately and evaluate balanced business outcomes.','Lead cross-functional incident response and durable improvement.'];
    if(state.screen===0)return `<section class="screen-panel review-screen"><span class="screen-eyebrow">Course Review</span><h3>What You Can Now Do</h3><div class="review-skill-list">${skills.map((v,i)=>`<div><span>${i+1}</span><p>${esc(v)}</p></div>`).join('')}</div></section>`;
    if(state.screen===1)return `<section class="screen-panel review-screen"><span class="screen-eyebrow">Key Takeaways</span><h3>The Advanced Fraud Framework</h3><div class="review-control-grid">${[['Connect the journey','Link accounts, identity, payments, fulfillment, support, refunds, and disputes.'],['Test hypotheses','Use supporting and contradicting evidence, defined measures, and safe tests.'],['Layer controls','Combine identity, authentication, devices, behavior, payments, velocity, networks, and review.'],['Measure trade-offs','Balance fraud, approval, customer experience, workload, and displacement.'],['Respond proportionately','Target the affected journey while protecting legitimate customers.'],['Govern improvement','Assign owners, monitoring, rollback, review dates, and source evidence.']].map(v=>`<article><h4>${esc(v[0])}</h4><p>${esc(v[1])}</p></article>`).join('')}</div></section>`;
    if(state.screen===2)return `<section class="screen-panel review-screen"><span class="screen-eyebrow">Resources</span><h3>Continue Your Learning</h3><div class="resource-list"><a href="https://owasp.org/www-project-automated-threats-to-web-applications/" target="_blank" rel="noopener"><strong>OWASP Automated Threats</strong><span>Catalog of automated business-logic threats</span></a><a href="https://pages.nist.gov/800-63-4/sp800-63b.html" target="_blank" rel="noopener"><strong>NIST Digital Identity Guidelines</strong><span>Authentication and authenticator guidance</span></a><a href="https://fidoalliance.org/passkeys/" target="_blank" rel="noopener"><strong>FIDO Alliance Passkeys</strong><span>Phishing-resistant authentication resources</span></a><a href="https://www.emvco.com/emv-technologies/3-d-secure/" target="_blank" rel="noopener"><strong>EMV 3-D Secure</strong><span>Card-not-present payment authentication</span></a><a href="https://www.pcisecuritystandards.org/document_library/" target="_blank" rel="noopener"><strong>PCI SSC Document Library</strong><span>Payment security standards and guidance</span></a></div></section>`;
    return `<section class="screen-panel completion-screen"><div class="completion-mark">✓</div><h3>You’ve completed the course</h3><p>Review the key learnings and resources, then continue to the final exam.</p><button id="exitBtn" class="primary-btn">Continue to Final Exam</button></section>`;
  };

  const baseRender = renderV4;
  renderV4 = function () {
    baseRender();
    const audioButton=document.getElementById('playScenarioAudioBtn');
    if(audioButton && ![0,1,2,3,4,5].includes(state.lesson)) audioButton.remove();
  };

  if (false) {
    state.courseVersion=16; state.lesson=0; state.screen=0; state.completed=[];
    state.visitedCards={}; state.scenarioComplete={}; state.kcComplete={}; state.reviewSeen={};
    state.overviewSeen=false; state.onOverview=false; state.examActive=false; state.examView='instructions';
    state.examQuestion=0; state.examAnswers={}; state.examAttempts=0; state.examPassed=false;
    state.examBestScore=0; state.examLastScore=0; state.examExhausted=false; save();
  }
})();
