// AFP 2026 research screens and complete six-lesson scenario audio support.
(function () {
  const sourceUrl='https://www.financialprofessionals.org/training-resources/resources/survey-research-economic-data/Details/payments-fraud';
  const researchScreens=[
    {title:'Payments Fraud Is Persistent and Connected',lead:'Current payment-fraud experience reinforces why teams need connected detection, response, and recovery rather than transaction-only controls.',metrics:[['76%','of surveyed organizations experienced attempted or actual payments fraud in 2025.'],['81% vs. 67%','Attack exposure was higher among organizations with at least $1 billion in revenue than among smaller organizations.'],['20%','of organizations experiencing payments fraud recovered none of the funds lost.']],actions:['Use attempted fraud, actual loss, recovery, and customer impact as separate outcome measures.','Link detection to an immediate escalation and recovery path.','Test whether the organization can contact banks, partners, vendors, and internal owners quickly enough to preserve recovery options.'],pages:'Key Highlights, pp. 3-6'},
    {title:'Impersonation Now Crosses Email, Phone, Text, and Video',lead:'Fraudsters can move between channels and use convincing context. Verification should follow trusted records, not the channel or contact details supplied in the request.',metrics:[['74%','of organizations were affected by business email compromise in 2025.'],['30%','reported fraudulent phone calls targeting the organization.'],['28%','reported scam texts on official mobile devices.']],actions:['Verify payment or contact changes through an authorized person using independently maintained contact information.','Treat urgency, secrecy, channel switching, and new payment details as process risks even when the message looks authentic.','Train Treasury, Accounts Payable, support, sales, and call-center teams on the same verification standard.'],pages:'Key Highlights, pp. 3 and 7-12'},
    {title:'Payment Method Changes the Fraud and Recovery Plan',lead:'Risk assessment should consider how each payment method is initiated, verified, settled, monitored, and recovered.',metrics:[['58%','of organizations reported check fraud, making checks the most frequently affected payment method.'],['30%','reported fraud involving ACH debits.'],['25%','reported fraud involving wire transfers.']],actions:['Maintain method-specific controls for payment setup, approval, release, reconciliation, and exception handling.','Use independent verification for new beneficiaries and payment-instruction changes.','Document the bank contact, recall or return process, evidence requirements, and time constraints for each payment rail.'],pages:'Key Highlights, pp. 3, 5, and 10'},
    {title:'Use AI Where It Improves a Defined Control',lead:'AI adoption remains limited, so organizations need disciplined use cases, outcome measures, and human oversight rather than broad automation claims.',metrics:[['17%','of surveyed organizations reported using AI to combat payments fraud.'],['49%','of AI users reported improved efficiency in fraud reporting.'],['45% and 43%','reported improved deepfake detection and real-time identification, respectively.']],actions:['Start with a measurable problem such as case prioritization, anomaly detection, network discovery, or reporting efficiency.','Run in shadow mode or limited rollout before consequential use.','Monitor label quality, drift, false positives, segment impact, analyst overrides, and rollback criteria.'],pages:'AFP press release and Key Highlights, p. 3'},
    {title:'Prevention Must Include Recovery Readiness',lead:'When fraud succeeds, recovery outcomes vary sharply. A mature program measures whether controls prevent loss and whether teams can act fast enough to recover funds.',metrics:[['30%','of affected organizations recovered more than 75% of funds lost.'],['20%','recovered none.'],['24%','of smaller organizations recovered none, and another 24% recovered less than 10%.']],actions:['Measure time from detection to escalation, bank notification, payment recall, customer contact, and case ownership.','Use independent callbacks for payment changes; AFP respondents rated this among the most effective BEC controls.','Include recovery cost, support workload, legitimate-customer impact, and unrecovered loss in control evaluation.'],pages:'Key Highlights, pp. 6 and 12'},
    {title:'Fraud Response Is an Operating Model',lead:'Detection and recovery often begin in Treasury, but effective response depends on coordinated decisions across Accounts Payable, banks, vendors, fraud, security, legal, and operations.',metrics:[['83%','cited Treasury as discovering attempted payments fraud.'],['55%','cited Treasury as discovering actual payments fraud.'],['465','corporate treasury professionals across industries and organization sizes participated in the survey.']],actions:['Define who validates the alert, contacts the bank, stops related payments, preserves evidence, and communicates with affected parties.','Keep independently maintained contact details for banks, vendors, and authorized approvers.','Run incident exercises that include detection, containment, recovery, displacement monitoring, and post-incident ownership.'],pages:'Key Highlights, pp. 2-3 and 14-16'}
  ];
  function renderResearchScreen(){const r=researchScreens[state.lesson];els.kicker.textContent=`Lesson ${String(state.lesson+1).padStart(2,'0')} of 07 · Current Landscape`;els.title.textContent=lessons[state.lesson].title;els.main.innerHTML=`<section class="screen-panel research-screen"><span class="screen-eyebrow">Current Payments Fraud Landscape</span><h3>${esc(r.title)}</h3><p class="research-lead">${esc(r.lead)}</p><div class="research-metrics">${r.metrics.map(m=>`<article><strong>${esc(m[0])}</strong><p>${esc(m[1])}</p></article>`).join('')}</div><div class="research-actions"><h4>Apply this finding</h4><ul>${r.actions.map(a=>`<li>${esc(a)}</li>`).join('')}</ul></div><p class="research-source"><strong>Source:</strong> Association for Financial Professionals, <em>2026 AFP Payments Fraud and Control Survey Report: Key Highlights</em>, ${esc(r.pages)}. Survey findings reflect 2025 activity reported by 465 corporate treasury practitioners. <a href="${sourceUrl}" target="_blank" rel="noopener">View the official AFP report page</a>.</p></section>`;updateV4();els.main.focus();window.scrollTo(0,0)}
  function renderExpandedLessonReview(){els.kicker.textContent=`Lesson ${String(state.lesson+1).padStart(2,'0')} of 07 · Lesson Review`;els.title.textContent=lessons[state.lesson].title;els.main.innerHTML=renderLessonReview();$$('.takeaway-card').forEach(b=>b.onclick=()=>{play('click');b.classList.toggle('open');b.setAttribute('aria-expanded',b.classList.contains('open'));b.querySelector('.takeaway-icon').textContent=b.classList.contains('open')?'−':'+'});updateV4();els.main.focus();window.scrollTo(0,0)}
  countV4=function(i=state.lesson){return i===6?4:10};
  labelV4=function(){if(state.lesson===6)return ['Course Review','Key Takeaways','Resources','Course Completion'][state.screen];return ['Lesson Introduction','Why It Matters','Core Concepts','Merchant Application','Deep Dive','Interactive Activity','Scenario','Knowledge Check','Current Landscape','Lesson Review'][state.screen]};
  const priorRender=renderV4;
  renderV4=function(){if(state.examActive||state.onOverview){priorRender();return}if(state.lesson===6||state.screen<8){priorRender();updateV4();return}if(state.screen===8)renderResearchScreen();else renderExpandedLessonReview()};
  updateV4=function(){const review=state.lesson===6,activity=state.screen===5&&!review,scenario=state.screen===6&&!review,kc=state.screen===7&&!review;els.back.disabled=state.lesson===0&&state.screen===0;els.next.disabled=(activity&&!allCardsSeen(state.lesson))||(scenario&&!state.scenarioComplete[state.lesson])||(kc&&!state.kcComplete[state.lesson]);els.next.textContent=state.screen===countV4()-1?(review?'Course Complete':'Next Lesson →'):'Next →';els.indicator.textContent=`Screen ${state.screen+1} of ${countV4()}`;const prior=state.lesson<6?state.lesson*10:60;const progress=Math.round((1+prior+state.screen+(state.completed.includes(6)?1:0))/65*100);els.bar.style.width=progress+'%';els.pct.textContent=progress+'%';els.status.textContent=state.completed.includes(state.lesson)?'Completed':labelV4();renderNavV3()};
  if(state.courseVersion!==18){state.courseVersion=18;state.lesson=0;state.screen=0;state.completed=[];state.visitedCards={};state.scenarioComplete={};state.kcComplete={};state.reviewSeen={};state.hotspotSelections=[];state.overviewSeen=false;state.onOverview=false;state.examActive=false;state.examView='instructions';state.examQuestion=0;state.examAnswers={};state.examAttempts=0;state.examPassed=false;state.examBestScore=0;state.examLastScore=0;state.examExhausted=false;save()}
})();
