const extraContent=[
 {title:"When Trust Signals Disagree",intro:"A strong operating model defines what happens when evidence is valid in one system but incomplete or conflicting in another.",paras:["A merchant may receive a valid agent signature and an issuer approval while the authorization record limits the purchase to a different category or amount. In that case, the merchant should not average the signals or allow the strongest technical signal to override the missing business authority.","Classify evidence by the question it answers. Agent identity evidence supports recognition of the requester. Customer authentication supports the delegation event. Mandates describe scope. Payment data supports the funding decision. Behavioral signals support risk assessment. When a required category is missing, route the transaction to clarification, step-up, or safe rejection."],takeaway:"Define minimum evidence requirements by transaction risk and record which requirement caused the decision."},
 {title:"Key Lifecycle and Trust Status",intro:"Agent identity remains trustworthy only while its keys, registration, and supporting trust records remain current.",paras:["Keys can expire, rotate, be suspended, or be compromised. A merchant that caches agent identity information indefinitely may continue accepting requests after the ecosystem has withdrawn trust. A merchant that refuses all cached information during a brief directory outage may create unnecessary disruption.","Set cache durations, status-check frequency, emergency revocation behavior, and outage handling according to risk. Preserve the key identifier and trust-record version used for each decision so investigators can reconstruct what the merchant knew at that time."],takeaway:"A valid signature proves control of a key. Current status evidence connects that key to a trusted agent at the time of the request."},
 {title:"From Customer Language to Enforceable Rules",intro:"Agent platforms and merchants need a controlled way to translate flexible customer instructions into structured scope.",paras:["The customer-facing instruction can remain natural and conversational, but the enforceable representation should identify required and optional constraints. For example, a travel request may include a maximum total price, dates, location radius, cancellation terms, room type, taxes, loyalty preferences, and whether the agent may select a nonrefundable rate.","Show the customer the resulting constraints before authority is granted. Preserve both the human-readable terms and the structured representation. If the agent cannot translate an important preference with confidence, request clarification rather than selecting a broader interpretation."],takeaway:"Good scope is understandable to the customer and deterministic for the systems that enforce it."},
 {title:"Designing a Useful Step-Up Experience",intro:"Step-up verification should resolve a specific uncertainty rather than simply add friction.",paras:["The prompt should explain why confirmation is needed and display the material transaction details. Include the merchant, item or service, final total, fees, payment source, delivery destination, timing, and whether approval applies once or changes future authority.","Protect the information between display and approval. If the cart changes after confirmation, compare the new version with the approved version and determine whether the difference is within an allowed tolerance. Avoid vague prompts such as ‘Approve agent purchase?’ that do not tell the customer what will happen."],takeaway:"A useful step-up binds strong authentication to the exact exception the customer is approving."},
 {title:"Aligning Token Scope with Customer Scope",intro:"Payment capability should not be broader than the authority the consumer granted whenever the ecosystem supports narrower controls.",paras:["A token limited to a merchant category may still work at many merchants the customer never approved. A long-lived token may remain usable after the mandate expires. A multi-use token may support repeated charges when the consumer approved only one purchase.","Document which party creates and controls each token, which domain restrictions are enforced, and how the token maps to the mandate and cart. Test delayed capture, split shipment, partial approval, retry, cancellation, return, and refund paths so stronger restrictions do not break legitimate post-purchase operations."],takeaway:"Minimize both credential exposure and credential usability, then preserve the lifecycle functions the merchant still needs."},
 {title:"Handling In-Flight Changes",intro:"Authority can change while an order is authorized, reviewed, packed, captured, or shipped.",paras:["Map every order state to the controls that can still act. Before acceptance, the merchant can reject or request clarification. After authorization but before capture, the merchant may be able to void the payment. After capture but before shipment, cancellation and refund may still be possible. After fulfillment, the response shifts to service, return, or dispute handling.","Real-time control depends on reliable event delivery and idempotent processing. Record when the change was issued, received, verified, and enforced. Define escalation for delayed or conflicting status messages."],takeaway:"Revocation and expiry protect customers only when the merchant can apply them at an actionable checkpoint."},
 {title:"Evidence Quality and Retention",intro:"Evidence must be usable, protected, and proportionate to the merchant’s legitimate operational and legal needs.",paras:["Record verification results and stable references rather than copying sensitive secrets into general logs. A decision record should identify the policy version, verified inputs, missing evidence, triggered rules, human actions, and final reason code.","Apply access controls, encryption, monitoring, retention schedules, deletion procedures, and regional requirements. Test whether authorized teams can retrieve a coherent evidence package without giving them access to unrelated customer data."],takeaway:"Auditability is strongest when evidence is linked and reproducible, not when every possible data element is retained indefinitely."}
];

const knowledgeChecks=[
 {type:'choice',prompt:'A recognized agent submits an issuer-approved order that exceeds the customer’s recorded amount limit. What should the merchant do?',choices:['Complete the order because two independent trust signals are valid.','Request fresh customer approval that is bound to the higher amount.','Permanently block the agent because the requested amount changed.'],correct:1,feedback:'Correct. Identity and payment approval do not replace scope validation. Fresh, bound approval can authorize the higher amount.'},
 {type:'choice',prompt:'Which verification sequence best protects a merchant from a replayed agent request?',choices:['Check the user-agent name, IP reputation, and payment result.','Verify the signature, then accept every request signed by that key.','Verify identity and signature coverage, then check freshness, status, audience, and replay identifiers.'],correct:2,feedback:'Correct. A valid signature must be combined with freshness, status, audience, and replay checks.'},
 {type:'match',prompt:'Match each scope question to the constraint that answers it.',pairs:[['Where may the agent buy?','Merchant'],['How much may it spend?','Amount'],['When must the customer return?','Confirmation']],options:['Amount','Confirmation','Merchant'],feedback:'Correct. Merchant, amount, and confirmation constraints answer different parts of the delegated authority.'},
 {type:'choice',prompt:'A valid standing mandate covers the category and amount, but the agent adds a new delivery address. What is the best response?',choices:['Request bound step-up approval for the new address and final order.','Accept the order because the existing mandate covers the purchase.','Cancel all delegated authority because the address changed.'],correct:0,feedback:'Correct. A targeted step-up resolves the material change without discarding otherwise valid authority.'},
 {type:'choice',prompt:'Which token design most closely follows least privilege for a one-time purchase?',choices:['A reusable token accepted by every merchant in the same category.','A token bound to the merchant, amount, use count, and authorization window.','An internal vault reference that never expires and can fund any future cart.'],correct:1,feedback:'Correct. Merchant, amount, use-count, and time limits align payment capability with the authorized purchase.'},
 {type:'match',prompt:'Match the mandate to the evidence it should capture.',pairs:[['Customer outcome and boundaries','Intent mandate'],['Final items, fees, and delivery terms','Cart mandate'],['Funding source, recipient, and amount','Payment mandate']],options:['Cart mandate','Intent mandate','Payment mandate'],feedback:'Correct. Each mandate represents a different stage of the customer’s authority and transaction.'},
 {type:'choice',prompt:'What makes an audit trail most useful for an agent-initiated transaction?',choices:['A large volume of raw logs retained without a defined schedule.','A final approve or decline result without the underlying evidence.','Linked identity, consent, cart, payment, decision, and fulfillment records.'],correct:2,feedback:'Correct. Linked records allow an authorized reviewer to reconstruct the transaction and the reason for the merchant’s action.'}
];

lessons.push({title:'Review and Resources',purpose:'Review the trust decisions, merchant controls, and resources presented throughout the course.',objectives:['Summarize the three trust questions that guide agent-mediated commerce.','Recall the controls that support identity, authorization, scope, payment, and evidence.','Identify resources for continued learning and implementation planning.'],intro:'This final lesson brings the course together and provides resources for continued learning.',cards:[],key:'Trustworthy agentic commerce depends on verifiable identity, bounded authority, real-time control, and linked evidence.'});

if(state.courseVersion!==3){state.courseVersion=3;state.lesson=0;state.screen=0;state.completed=[];state.visitedCards={};state.scenarioComplete={};state.kcComplete={};state.reviewSeen={}}
state.scenarioComplete=state.scenarioComplete||{};state.kcComplete=state.kcComplete||{};state.reviewSeen=state.reviewSeen||{};

function countV3(i=state.lesson){return i===6?4:8}
function labelV3(){if(state.lesson===6)return ['Course Review','Key Takeaways','Resources','Course Completion'][state.screen];return ['Lesson Introduction','Why It Matters','Core Concepts','Merchant Application','Deep Dive','Interactive Activity','Scenario','Knowledge Check'][state.screen]}
function setV3(n){state.screen=Math.max(0,Math.min(countV3()-1,n));renderV3();save()}
function addCompleted(i){if(!state.completed.includes(i))state.completed.push(i);state.completed.sort((a,b)=>a-b);save()}
function renderMatch(kc){return `<div class="match-grid">${kc.pairs.map((p,i)=>`<label><span>${esc(p[0])}</span><select data-match="${i}"><option value="">Select a match</option>${kc.options.map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('')}</select></label>`).join('')}</div><button id="checkMatch" class="primary-btn small">Check Answers</button>`}
function renderReviewScreen(){
 const review=[['Recognize the agent','Verify identity, signature coverage, freshness, audience, and current status.'],['Confirm delegated authority','Connect the action to an authenticated consumer and an active grant.'],['Enforce scope','Compare the final merchant, item, amount, timing, delivery, and payment terms with the grant.'],['Apply proportionate step-up','Return to the customer when a material change or risk condition requires fresh approval.'],['Protect payment capability','Use tokenization and limits that align the credential with the authorized purchase.'],['Honor real-time control','Enforce expiration, revocation, and supersession while the transaction can still be stopped.'],['Preserve linked evidence','Connect identity, consent, cart, payment, decision, and fulfillment records.']];
 if(state.screen===0)return `<section class="screen-panel review-screen"><span class="screen-eyebrow">Course Review</span><h3>What You Can Now Do</h3><p class="section-lead">By completing this course, you have developed the following skills and knowledge:</p><div class="review-skill-list">${['Separate agent identity, customer authorization, and scope compliance.','Evaluate cryptographic and contextual agent identity signals.','Interpret delegated authority and structured scope.','Apply passkeys and targeted step-up verification.','Align token controls with customer authorization.','Enforce consent, expiry, revocation, and supersession.','Use audit evidence to support decisions and investigations.'].map((v,i)=>`<div><span>${i+1}</span><p>${esc(v)}</p></div>`).join('')}</div></section>`;
 if(state.screen===1)return `<section class="screen-panel review-screen"><span class="screen-eyebrow">Key Takeaways</span><h3>Trust Controls at a Glance</h3><div class="review-control-grid">${review.map(v=>`<article><h4>${esc(v[0])}</h4><p>${esc(v[1])}</p></article>`).join('')}</div></section>`;
 if(state.screen===2)return `<section class="screen-panel review-screen"><span class="screen-eyebrow">Resources</span><h3>Continue Your Learning</h3><p class="section-lead">These primary resources provide additional detail on agent protocols, authentication, authorization, and payment tokenization.</p><div class="resource-list"><a href="https://developers.googleblog.com/developers-guide-to-ai-agent-protocols/" target="_blank" rel="noopener"><strong>Google Developer’s Guide to AI Agent Protocols</strong><span>Typed mandates and agent protocol concepts</span></a><a href="https://developer.visa.com/capabilities/trusted-agent-protocol/trusted-agent-protocol-specifications" target="_blank" rel="noopener"><strong>Visa Trusted Agent Protocol Specifications</strong><span>Recognizing approved agents and verifying request data</span></a><a href="https://fidoalliance.org/passkeys/" target="_blank" rel="noopener"><strong>FIDO Alliance Passkeys</strong><span>Passkey authentication fundamentals</span></a><a href="https://www.emvco.com/emv-technologies/payment-tokenisation/" target="_blank" rel="noopener"><strong>EMV Payment Tokenisation</strong><span>Payment token roles, functions, and domain controls</span></a><a href="https://www.rfc-editor.org/rfc/rfc9700.html" target="_blank" rel="noopener"><strong>OAuth 2.0 Security Best Current Practice</strong><span>Current security guidance for delegated authorization</span></a></div></section>`;
 return `<section class="screen-panel completion-screen"><div class="completion-mark">✓</div><h3>You’ve completed the course</h3><p>Please review the course key learnings and resources before exiting to take the final exam.</p><button id="exitBtn" class="primary-btn">Exit Course</button></section>`;
}

function renderV3(){
 const l=lessons[state.lesson];els.kicker.textContent=`Lesson ${String(state.lesson+1).padStart(2,'0')} of 07 · ${labelV3()}`;els.title.textContent=l.title;let html='';
 if(state.lesson===6){html=renderReviewScreen();els.main.innerHTML=html;if(state.screen===3)addCompleted(6);const exit=$('#exitBtn');if(exit)exit.onclick=()=>{play('click');if(window.SCORM)SCORM.complete();toast('Course completion recorded');setTimeout(()=>{try{window.close()}catch(e){}},500)};updateV3();els.main.focus();window.scrollTo(0,0);return}
 const x=screenContent[state.lesson],e=extraContent[state.lesson];
 if(state.screen===0)html=`<section class="screen-panel intro-screen"><span class="screen-eyebrow">Lesson ${state.lesson+1}</span><h3>${esc(l.title)}</h3><p class="lead">${esc(l.purpose)}</p><div class="objectives"><h4>By the end of this lesson, you will be able to:</h4><ul>${l.objectives.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div></section>`;
 if(state.screen===1)html=`<section class="screen-panel"><span class="screen-eyebrow">Why It Matters</span><h3>${esc(x.whyTitle||"Why This Matters")}</h3>${x.why.map(v=>`<p class="body-copy">${esc(v)}</p>`).join('')}<div class="key-callout"><strong>Key principle:</strong> ${esc(l.key)}</div></section>`;
 if(state.screen===2)html=`<section class="screen-panel"><span class="screen-eyebrow">Core Concepts</span><h3>${esc(x.conceptsTitle||"Core Concepts")}</h3><p class="section-lead">${esc(x.conceptsIntro||"Review the concepts that support this decision.")}</p>${conceptGrid(x.concepts)}</section>`;
 if(state.screen===3)html=`<section class="screen-panel"><span class="screen-eyebrow">What Merchants Can Do</span><h3>${esc(x.applyTitle)}</h3><p class="section-lead">${esc(x.applyIntro)}</p><ol class="application-list">${x.apply.map(v=>`<li>${esc(v)}</li>`).join('')}</ol></section>`;
 if(state.screen===4)html=`<section class="screen-panel deep-dive"><span class="screen-eyebrow">In Practice</span><h3>${esc(e.title)}</h3><p class="section-lead">${esc(e.intro)}</p>${e.paras.map(v=>`<p class="body-copy">${esc(v)}</p>`).join('')}<div class="key-callout"><strong>Remember:</strong> ${esc(e.takeaway)}</div></section>`;
 if(state.screen===5){const cards=l.cards.map((c,j)=>`<button class="toggle-card" data-card="${j}" aria-expanded="false"><strong>${esc(c[0])}</strong><span class="front-copy">${esc(c[1])}</span><span class="back-copy">${esc(c[2])}</span></button>`).join('');html=`<section class="screen-panel"><span class="screen-eyebrow">Interactive Activity</span><h3>${esc(l.activityTitle||'Explore the Controls')}</h3><p class="section-lead">${esc(l.activityIntro||'Select each card to explore the lesson concepts.')}</p><p class="instruction">Select a card to reveal the explanation. Select it again to return to the first side.</p><div class="toggle-grid">${cards}</div><div class="activity-status" role="status">${allCardsSeen(state.lesson)?'Activity complete. You may continue.':`${(state.visitedCards[state.lesson]||[]).length} of ${l.cards.length} cards reviewed`}</div></section>`}
 if(state.screen===6){const done=state.scenarioComplete[state.lesson];html=`<section class="scenario-stage"><p class="scenario-intro compact">${esc(l.scenario.intro)}</p><div class="scenario-card compact-scenario"><div class="character-pane"><img src="assets/character-${state.lesson+1}.png" alt="Professional guiding the scenario"></div><div class="scenario-copy"><h3>Scenario: ${esc(l.scenario.title)}</h3>${l.scenario.body.map(v=>`<p>${esc(v)}</p>`).join('')}<p class="scenario-question">${esc(l.scenario.question)}</p><div class="choice-list">${l.scenario.choices.map((v,j)=>`<button class="choice-btn ${done&&j===l.scenario.correct?'correct':''}" data-choice="${j}" ${done?'disabled':''}>${esc(v)}</button>`).join('')}</div><div class="incorrect-box" role="alert">Try again</div><div class="feedback ${done?'show':''}" role="status"><strong>Correct</strong><br>${esc(l.scenario.feedback)}</div></div></div></section>`}
 if(state.screen===7){const kc=knowledgeChecks[state.lesson],done=state.kcComplete[state.lesson];html=`<section class="screen-panel kc-screen"><span class="screen-eyebrow">Knowledge Check</span><h3>Check Your Understanding</h3><p class="kc-prompt">${esc(kc.prompt)}</p>${kc.type==='choice'?`<div class="kc-choices">${kc.choices.map((v,j)=>`<button class="choice-btn ${done&&j===kc.correct?'correct':''}" data-kc="${j}" ${done?'disabled':''}>${esc(v)}</button>`).join('')}</div>`:renderMatch(kc)}<div class="incorrect-box kc-error" role="alert">Try again</div><div class="feedback kc-feedback ${done?'show':''}" role="status"><strong>Correct</strong><br>${esc(kc.feedback)}</div></section>`}
 els.main.innerHTML=html;
 if(state.screen===5)$$('.toggle-card').forEach(b=>b.onclick=()=>{play('click');b.classList.toggle('open');b.setAttribute('aria-expanded',b.classList.contains('open'));const i=+b.dataset.card;state.visitedCards[state.lesson]=state.visitedCards[state.lesson]||[];if(!state.visitedCards[state.lesson].includes(i))state.visitedCards[state.lesson].push(i);$('.activity-status').textContent=allCardsSeen(state.lesson)?'Activity complete. You may continue.':`${state.visitedCards[state.lesson].length} of ${l.cards.length} cards reviewed`;updateV3();save()});
 if(state.screen===6)$$('.choice-btn').forEach(b=>b.onclick=()=>{play('click');if(+b.dataset.choice===l.scenario.correct){state.scenarioComplete[state.lesson]=true;b.classList.add('correct');$$('.choice-btn').forEach(v=>v.disabled=true);$('.incorrect-box').classList.remove('show');$('.feedback').classList.add('show');updateV3();save()}else{$('.incorrect-box').classList.add('show');b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),350)}});
 if(state.screen===7){const kc=knowledgeChecks[state.lesson];if(kc.type==='choice')$$('[data-kc]').forEach(b=>b.onclick=()=>{play('click');if(+b.dataset.kc===kc.correct){state.kcComplete[state.lesson]=true;addCompleted(state.lesson);b.classList.add('correct');$$('[data-kc]').forEach(v=>v.disabled=true);$('.kc-error').classList.remove('show');$('.kc-feedback').classList.add('show');updateV3()}else{$('.kc-error').classList.add('show');b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),350)}});else $('#checkMatch').onclick=()=>{play('click');const vals=$$('[data-match]').map(s=>s.value),correct=kc.pairs.every((p,i)=>vals[i]===p[1]);if(correct){state.kcComplete[state.lesson]=true;addCompleted(state.lesson);$$('[data-match]').forEach(s=>s.disabled=true);$('#checkMatch').disabled=true;$('.kc-error').classList.remove('show');$('.kc-feedback').classList.add('show');updateV3()}else $('.kc-error').classList.add('show')}}
 updateV3();els.main.focus();window.scrollTo(0,0);
}

function updateV3(){const isReview=state.lesson===6,activity=state.screen===5&&!isReview,scenario=state.screen===6&&!isReview,kc=state.screen===7&&!isReview;els.back.disabled=state.lesson===0&&state.screen===0;els.next.disabled=(activity&&!allCardsSeen(state.lesson))||(scenario&&!state.scenarioComplete[state.lesson])||(kc&&!state.kcComplete[state.lesson]);els.next.textContent=state.screen===countV3()-1?(state.lesson===6?'Course Complete':'Next Lesson →'):'Next →';els.indicator.textContent=`Screen ${state.screen+1} of ${countV3()}`;const priorScreens=state.lesson<6?state.lesson*8:48,p=Math.round((priorScreens+state.screen+(state.completed.includes(6)?1:0))/52*100);els.bar.style.width=p+'%';els.pct.textContent=p+'%';els.status.textContent=state.completed.includes(state.lesson)?'Completed':labelV3();renderNavV3()}
function renderNavV3(){els.nav.innerHTML=lessons.map((l,i)=>`<button class="lesson-link ${i===state.lesson?'active':''} ${state.completed.includes(i)?'complete':''}" data-i="${i}" ${isUnlocked(i)?'':'disabled'}><span class="lesson-num">${state.completed.includes(i)?'✓':i+1}</span><span class="lesson-copy">${esc(l.title)}</span><span class="lock">${isUnlocked(i)?'':'🔒'}</span></button>`).join('');$$('.lesson-link').forEach(b=>b.onclick=()=>{play('click');state.lesson=+b.dataset.i;state.screen=0;renderV3();save();if(innerWidth<900)els.side.classList.remove('mobile-open')})}

$('#startBtn').onclick=()=>{state.started=true;state.lesson=0;state.screen=0;els.start.classList.add('hidden');els.shell.classList.remove('hidden');play('menu');renderV3();save()};$('#resumeBtn').onclick=()=>{state.started=true;els.start.classList.add('hidden');els.shell.classList.remove('hidden');play('menu');renderV3();save()};els.back.onclick=()=>{play('click');if(state.screen>0){state.screen--;renderV3();save()}else if(state.lesson>0){state.lesson--;state.screen=countV3()-1;renderV3();save()}};els.next.onclick=()=>{if(els.next.disabled)return;play('click');if(state.screen<countV3()-1){state.screen++;renderV3();save()}else if(state.lesson<6){state.lesson++;state.screen=0;renderV3();save()}else toast('Course complete. Select Exit Course.')};
